### ISSUE TITLE
Navigation-drawer-page-sliding-tab-strip

### ISSUE THREAD

**Issue by nehalgoyal** [balaji-k13/Navigation-drawer-page-sliding-tab-strip#8]
I want to add search contacts in tab 1... 
I face problem it can not search contacts from my phone book...
plzz help me...
its shows problem in 

private void setupSearchView() 
{
SearchManager searchManager = (SearchManager) getActivity().getSystemService(Context.SEARCH_SERVICE);
//error in findViewById
final SearchView searchView = (SearchView)findViewById(R.id.searchView);
SearchableInfo searchableInfo = searchManager.getSearchableInfo(getActivity().getComponentName());
        searchView.setSearchableInfo(searchableInfo);
    }

**Comment by balaji-k13** [comment]
What is the error?

**Comment by balaji-k13** [comment]
any queries , contact balaji1308@gmail.com , I won't be online on github always.

**Comment by balaji-k13** [comment]
generally findViewById() will be called from onViewCreated(View view, Bundle savedInstanceState) -- via view.findViewById(R.id.searchView)
